{% set name = "climepi" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/will-s-hart/climate-epidemics/archive/v{{ version }}.tar.gz
  sha256: 306bf6db259f0623b52f9697e12416615137d51ad26fdf1241d8397f5d6fab3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - dask >=2024.11.2
    - datashader
    - flox
    - geopy
    - geoviews
    - hvplot
    - intake
    - intake-esm
    - nc-time-axis
    - numpy
    - pandas
    - panel
    - param
    - pooch
    - requests
    - s3fs
    - urllib3
    - xarray !=2024.10.0
    - xcdat


test:
  requires:
    - python {{ python_min }}
  imports:
    - climepi
    - climepi.climdata
    - climepi.epimod
    - climepi.app

about:
  home: https://will-s-hart.github.io/climate-epidemics
  summary: Combining climate data and epidemiological models
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://climate-epidemics.readthedocs.io/en/latest/
  dev_url: https://github.com/will-s-hart/climate-epidemics

extra:
  recipe-maintainers:
    - will-s-hart
