context:
  name: climepi
  version: "0.6.3"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/idm-oxford/climate-epidemics/archive/v${{ version }}.tar.gz
  sha256: 5726a4b491e217bf0c404227956cb8239db3e078531da8f2a0c12f314c137c6e

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - hatchling >=1.28
    - version-pioneer >=0.0.14
    - pip
  run:
    - python >=${{ python_min }}
    - arviz-base
    - bottleneck
    - dask
    - datashader
    - flox
    - geopy
    - geoviews
    - h5netcdf
    - hvplot
    - intake
    - intake-esm
    - kerchunk >=0.2.9
    - nc-time-axis
    - numpy
    - pandas
    - panel
    - param
    - pooch
    - pydantic
    - pymc
    - requests
    - s3fs >=2021.4
    - scipy
    - siphon
    - tqdm
    - typing-extensions
    - urllib3
    - xarray !=2025.7
    - xcdat

tests:
  - python:
      imports:
        - climepi
        - climepi.climdata
        - climepi.epimod
        - climepi.app
      pip_check: false
      python_version: "${{ python_min }}.*"


about:
  summary: Combining climate data and epidemiological models
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/idm-oxford/climate-epidemics
  repository: https://github.com/idm-oxford/climate-epidemics
  documentation: https://climate-epidemics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - will-s-hart
