context:
  name: climepi
  version: "0.5.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/idm-oxford/climate-epidemics/archive/v${{ version }}.tar.gz
  sha256: 85cf9f1ec19f40c8a8ed1320b3dba13e48d6f9df8e38bd5dc9b3831a219de901

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - setuptools >=61.0
    - versioneer ==0.29
    - pip
  run:
    - python >=${{ python_min }}
    - bottleneck
    - dask >=2024.11.2
    - datashader
    - flox
    - geopy
    - geoviews
    - hvplot
    - intake
    - intake-esm
    - nc-time-axis
    - numpy
    - pandas
    - panel
    - param
    - pooch
    - requests
    - s3fs
    - scipy
    - urllib3
    - xarray !=2024.10.0
    - xcdat

tests:
  - python:
      imports:
        - climepi
        - climepi.climdata
        - climepi.epimod
        - climepi.app
      pip_check: false
      python_version: ==${{ python_min }}

about:
  summary: Combining climate data and epidemiological models
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://idm-oxford.github.io/climate-epidemics
  repository: https://github.com/idm-oxford/climate-epidemics
  documentation: https://climate-epidemics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - will-s-hart
